const constants = {
  userInfo: "userInfo",
  success: "Success",
  failed: "Failed",
  passed: "Passed",
  regex: {
    mobile: /^(\+91-|\+91|0)?\d{10}$/,
    password: /^(?=.{8,})(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%&*]).*$/,
    numbers: /^[0-9]*$/,
    amount: /^[0-9]*\.?([0-9]{1,2})$/,
    shortName: /^[a-zA-Z ,-.'&]*$/,
    // text: /^[a-zA-Z0-9,-.'&\/# ]*$/,
    // email: /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})$/,
    emailWithMaxLength: /^(?=.{1,100}$)[_a-zA-Z0-9-]+(\.[_a-zA-Z0-9-]+)*@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*(\.[a-zA-Z]{2,4})$/,
    alphabetsAndNumbers: /^[a-zA-Z0-9]*$/,
    socialHandle: /^[a-zA-Z0-9,-._#:/]*$/,
    alphabetsOnly: /^[a-zA-Z]*$/,
    // idRegex: /^[a-zA-Z0-9,-.'&\/# ]*$/,
    url: /(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})/,
    commaSeparatedEmails: /^[\W]*([\w+\-.%]+@[\w\-.]+\.[A-Za-z]{2,4}[\W]*,{1}[\W]*)*([\w+\-.%]+@[\w\-.]+\.[A-Za-z]{2,4})[\W]*$/,
    phone: /^(\+91-|\+91|0)?\d{10}$/,
  },
  fieldLengths: {
    firstName: 45,
    lastName: 45,
    mobile: 10,
    email: 50,
    password: 32,

    companyRegistrationNumber: 100,
    branchName: 30,
    fixedLine: 10,
    landmark: 100,
    pincode: 10,
    address: 100,
    idNumber: 30,
    cheque: 6,
    amount: 14,
    relation: 30,
    issuePlace: 30,
    fbId: 100,
    twitterHandle: 100,
    description: 30,
    commentNote: 250,
    OTP: 6,
    creditCard: 5,
    debitCard: 5,
    phoneWithHyphens: 12,
  },
  dateFormat: {
    fullMonthFirstFull: "MMMM DD, YYYY",
    full: "DD MMM YYYY hh:mm A",
    fullWithSec: "DD-MMM-YYYY hh:mm:ss A",
    date: "DD MMM YYYY",
    reverseDate: "YYYY-MM-DD",
    time: "hh:mm A",
    timeWithSec: "hh:mm:ss A",
    fullDateMonthWithTime: "DD MMM YYYY HH:mm",
    fullDateMonth: "DD MMM YYYY",
    dob: "DD-MM-YYYY",
    dateMonth: "DD MMMM",
    fullMonth: "MMM",
    fullDay: "dddd",
    dateYear: "YYYY",
    shortData: "DD-MMM, YYYY",
    invoiceDate: "DD MMM.YYYY",
    onlyTime: "hh:mm:ss",
  },
};

export default constants;
